export const thaiProvinces = [
  "กรุงเทพมหานคร",
  "กระบี่",
  "กาญจนบุรี",
  "กาฬสินธุ์",
  "กำแพงเพชร",
  "ขอนแก่น",
  "จันทบุรี",
  "ฉะเชิงเทรา",
  "ชลบุรี",
  "ชัยนาท",
  "ชัยภูมิ",
  "ชุมพร",
  "เชียงราย",
  "เชียงใหม่",
  "ตรัง",
  "ตราด",
  "ตาก",
  "นครนายก",
  "นครปฐม",
  "นครพนม",
  "นครราชสีมา",
  "นครศรีธรรมราช",
  "นครสวรรค์",
  "นนทบุรี",
  "นราธิวาส",
  "น่าน",
  "บึงกาฬ",
  "บุรีรัมย์",
  "ปทุมธานี",
  "ประจวบคีรีขันธ์",
  "ปราจีนบุรี",
  "ปัตตานี",
  "พระนครศรีอยุธยา",
  "พังงา",
  "พัทลุง",
  "พิจิตร",
  "พิษณุโลก",
  "เพชรบุรี",
  "เพชรบูรณ์",
  "แพร่",
  "พะเยา",
  "ภูเก็ต",
  "มหาสารคาม",
  "มุกดาหาร",
  "แม่ฮ่องสอน",
  "ยะลา",
  "ยโสธร",
  "ร้อยเอ็ด",
  "ระนอง",
  "ระยอง",
  "ราชบุรี",
  "ลพบุรี",
  "ลำปาง",
  "ลำพูน",
  "เลย",
  "ศรีสะเกษ",
  "สกลนคร",
  "สงขลา",
  "สตูล",
  "สมุทรปราการ",
  "สมุทรสงคราม",
  "สมุทรสาคร",
  "สระแก้ว",
  "สระบุรี",
  "สิงห์บุรี",
  "สุโขทัย",
  "สุพรรณบุรี",
  "สุราษฎร์ธานี",
  "สุรินทร์",
  "หนองคาย",
  "หนองบัวลำภู",
  "อ่างทอง",
  "อุดรธานี",
  "อุทัยธานี",
  "อุตรดิตถ์",
  "อุบลราชธานี",
  "อำนาจเจริญ"
];

// English names for reference (optional)
export const thaiProvincesEnglish = [
  "Bangkok",
  "Krabi",
  "Kanchanaburi",
  "Kalasin",
  "Kamphaeng Phet",
  "Khon Kaen",
  "Chanthaburi",
  "Chachoengsao",
  "Chonburi",
  "Chainat",
  "Chaiyaphum",
  "Chumphon",
  "Chiang Rai",
  "Chiang Mai",
  "Trang",
  "Trat",
  "Tak",
  "Nakhon Nayok",
  "Nakhon Pathom",
  "Nakhon Phanom",
  "Nakhon Ratchasima",
  "Nakhon Si Thammarat",
  "Nakhon Sawan",
  "Nonthaburi",
  "Narathiwat",
  "Nan",
  "Bueng Kan",
  "Buriram",
  "Pathum Thani",
  "Prachuap Khiri Khan",
  "Prachinburi",
  "Pattani",
  "Phra Nakhon Si Ayutthaya",
  "Phang Nga",
  "Phatthalung",
  "Phichit",
  "Phitsanulok",
  "Phetchaburi",
  "Phetchabun",
  "Phrae",
  "Phayao",
  "Phuket",
  "Maha Sarakham",
  "Mukdahan",
  "Mae Hong Son",
  "Yala",
  "Yasothon",
  "Roi Et",
  "Ranong",
  "Rayong",
  "Ratchaburi",
  "Lopburi",
  "Lampang",
  "Lamphun",
  "Loei",
  "Sisaket",
  "Sakon Nakhon",
  "Songkhla",
  "Satun",
  "Samut Prakan",
  "Samut Songkhram",
  "Samut Sakhon",
  "Sa Kaeo",
  "Saraburi",
  "Sing Buri",
  "Sukhothai",
  "Suphan Buri",
  "Surat Thani",
  "Surin",
  "Nong Khai",
  "Nong Bua Lamphu",
  "Ang Thong",
  "Udon Thani",
  "Uthai Thani",
  "Uttaradit",
  "Ubon Ratchathani",
  "Amnat Charoen"
];

// Helper function to get province by index
export const getProvinceByIndex = (index) => {
  return thaiProvinces[index] || "";
};

// Helper function to get English name by index
export const getProvinceEnglishByIndex = (index) => {
  return thaiProvincesEnglish[index] || "";
};

// Helper function to find province index by name (Thai or English)
export const findProvinceIndex = (name) => {
  const thaiIndex = thaiProvinces.findIndex(province => 
    province.toLowerCase().includes(name.toLowerCase())
  );
  
  if (thaiIndex !== -1) return thaiIndex;
  
  const englishIndex = thaiProvincesEnglish.findIndex(province => 
    province.toLowerCase().includes(name.toLowerCase())
  );
  
  return englishIndex;
};
